version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "test"
  - "push"
  - "transfer"

steps:
  main_clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "TomHart/anxiety-app"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  build_image:
    title: Building Docker Image
    type: build
    arguments:
      image_name: '${{CF_REPO_NAME}}'
      tag: latest

  push_image:
    type: push
    arguments:
      candidate: ${{build_image}}
      tag: latest
      image_name: '${{CF_REPO_NAME}}'
      registry: Private

  transfer:
    title: "Transferring to server"
    type: "freestyle"
    stage: "transfer"
    arguments:
      image: "ictu/sshpass:latest"
      commands:
        - "echo | ssh-keygen -P '' -t rsa"
        - "sshpass -p $PASSWORD ssh-copy-id -i /root/.ssh/id_rsa.pub -o StrictHostKeyChecking=no $USER@$HOST"
        - "scp -r deployments/test/ $USER@$HOST:~/${{CF_REPO_NAME}}/"
        - "ssh $USER@$HOST 'cd ~/${{CF_REPO_NAME}}/test && ./deploy.sh'"



