name: "Build, Deploy, and Push"
on: [ push ]
jobs:
    build-push:
        runs-on:
            - self-hosted
        steps:
#            -   name: Set up QEMU
#                uses: docker/setup-qemu-action@v2
            -   name: Set up Docker Context for Buildx
                id: buildx-context
                run: |
                    docker context create builders
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2
                with:
                    endpoint: builders
            -   name: Login to Docker Registry
                uses: docker/login-action@v2
                with:
                    registry: ${{ secrets.DOCKER_REGISTRY }}
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
            -   name: Build and push
                uses: docker/build-push-action@v3
                with:
                    push: true
                    tags: registry.tom-hart.net/anxiety-app:${{ github.ref_name }}